In [ ]:
1.state the difference between the numpy array and lists

In [ ]:
Arrays are homogeneous data whereas the lists are homogeneous and heterogeneous
Elementwise operation is possible in arrays but not possible in the list
Arrays are very useful for multidimensional data.

In [ ]:
2.Write a Code to create 50 evenly spaced numbers between 0 to 10.

In [1]:
import numpy as np

In [2]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
3.Write a Code to create an array of shape (4,5) with random samples with random seed 7

In [8]:
np.random.seed(7)
arr=np.random.random((4,5))
arr

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951],
       [0.53849587, 0.50112046, 0.07205113, 0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904, 0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923]])

In [ ]:
4.Create an 1D array starting from 0 ending with 100 with stepsize 10 and another array starting from 1000 ending with 10000 with stepsize 1000 and then concatenate two arrays created.

In [15]:
arr1=np.arange(0,100,10)
arr1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
arr2=np.arange(1000,10000,1000)
arr2

array([1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000])

In [19]:
arr3=np.concatenate((arr1,arr2))
arr3

array([   0,   10,   20,   30,   40,   50,   60,   70,   80,   90, 1000,
       2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000])

In [ ]:
5.Use array created in Q5 and replace the values lesser than 50 as <50.

In [20]:
np.where(arr3<50,'<50',arr3)

array(['<50', '<50', '<50', '<50', '<50', '50', '60', '70', '80', '90',
       '1000', '2000', '3000', '4000', '5000', '6000', '7000', '8000',
       '9000'], dtype='<U11')

In [ ]:
Q7) Write a Code to create 1D, 2D and 3D arrays randomly.

In [21]:
np.random.rand(5)

array([0.60054892, 0.9501295 , 0.23030288, 0.54848992, 0.90912837])

In [22]:
np.random.rand(2,5)

array([[0.13316945, 0.52341258, 0.75040986, 0.66901324, 0.46775286],
       [0.20484909, 0.49076589, 0.37238469, 0.47740115, 0.36589039]])

In [23]:
np.random.rand(3,2,2)

array([[[0.83791799, 0.76864751],
        [0.31399468, 0.57262533]],

       [[0.27604905, 0.45284293],
        [0.35297837, 0.65739946]],

       [[0.37035108, 0.45909298],
        [0.71932412, 0.41299183]]])

In [ ]:
8. Write a Code to create an array with 10 random integers within 100.

In [25]:
np.random.randint(0,100,10)

array([93, 81, 31,  2, 83, 50, 18, 21, 67, 75])

In [ ]:
9. Create a array with an sample data with shape of (5,4) with standard normal distribution with random seed of 201.

In [28]:
np.random.seed(201)
arr = np.random.normal(loc=0,scale=1,size=(5,4))
arr

array([[ 0.31678346, -0.4934171 ,  1.21794581,  0.43677076],
       [-0.72769267,  0.43030744, -0.68666532, -0.45301801],
       [-0.73285921, -0.75362743, -0.83251892,  0.44987187],
       [ 1.80752304, -0.48953136,  0.88158874, -0.69834087],
       [-0.0499747 ,  1.90752236, -0.32762267,  1.15003185]])

In [29]:
##9.Use the array from Q9 and create a dataframe with index=['L','M','N','O','P'], columns=['A','B','C','D']

SyntaxError: invalid syntax (<ipython-input-29-450953371bf9>, line 1)

In [31]:
import pandas as pd

In [33]:
pd.DataFrame(arr,index=['L','M','N','O','P'],columns=['A','B','C','D'])

A         B         C         D
L  0.316783 -0.493417  1.217946  0.436771
M -0.727693  0.430307 -0.686665 -0.453018
N -0.732859 -0.753627 -0.832519  0.449872
O  1.807523 -0.489531  0.881589 -0.698341
P -0.049975  1.907522 -0.327623  1.150032

In [34]:
 11.Find the most frequent value in an numpy 1D array. Use array x = np.array([10,20,66,20,10,30,50,60,70,60,66,12,13,66])

SyntaxError: invalid syntax (<ipython-input-34-fb589c522ebb>, line 1)

In [35]:
x = np.array([10,20,66,20,10,30,50,60,70,60,66,12,13,66])
print(x)
  
print("Most frequent value in the array is:",np.bincount(x).argmax())

[10 20 66 20 10 30 50 60 70 60 66 12 13 66]
Most frequent value in the array is: 66


In [ ]:
 Write a Code to Flatten a 2d array into 1d array. Use array: np.array([[1,2,3],[8,9,10],[11,22,33]])

In [36]:
arr4= np.array([[1,2,3],[8,9,10],[11,22,33]])

In [37]:
arr4

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [11, 22, 33]])

In [38]:
arr4.flatten()

array([ 1,  2,  3,  8,  9, 10, 11, 22, 33])

In [ ]:
##1) Import required libraries and read the provided dataset (youtube_dislike_dataset.csv) and retrieve top 5 and bottom 5 records.

In [39]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [45]:
pip install opendatasets

  Created wheel for kaggle: filename=kaggle-1.5.12-py3-none-any.whl size=73053 sha256=ef992120a9dcdc4ad9a2b3f2db061ee431c2beb7267965fbb4d64a99b7ccf0c7
  Stored in directory: c:\users\thenu\appdata\local\pip\cache\wheels\29\da\11\144cc25aebdaeb4931b231e25fd34b394e6a5725cbb2f50106
Successfully built kaggle
Note: you may need to restart the kernel to use updated packages.


In [2]:
import opendatasets as od

In [4]:
od.download("https://www.kaggle.com/datasets/dmitrynikolaev/youtube-dislikes-dataset")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: theu101@gmail.com
Your Kaggle Key: ········


ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Length': '0', 'Date': 'Sat, 25 Jun 2022 18:30:12 GMT', 'Access-Control-Allow-Credentials': 'true', 'Set-Cookie': 'ka_sessionid=8b75a80edc0d4f848aed1a4658682e5f; max-age=2626560; path=/, GCLB=CJn1kdOfhbvXtgE; path=/; HttpOnly', 'Turbolinks-Location': 'https://www.kaggle.com/api/v1/datasets/download/dmitrynikolaev/youtube-dislikes-dataset', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Content-Security-Policy': "object-src 'none'; script-src 'nonce-89qxe8OPWZIs5L1GcOzlHQ==' 'report-sample' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; frame-src 'self' https://www.kaggleusercontent.com https://www.youtube.com/embed/ https://polygraph-cool.github.io https://www.google.com/recaptcha/ https://form.jotform.com https://submit.jotform.us https://submit.jotformpro.com https://submit.jotform.com https://www.docdroid.com https://www.docdroid.net https://kaggle-static.storage.googleapis.com https://kaggle-static-staging.storage.googleapis.com https://kkb-dev.jupyter-proxy.kaggle.net https://kkb-staging.jupyter-proxy.kaggle.net https://kkb-production.jupyter-proxy.kaggle.net https://kkb-dev.firebaseapp.com https://kkb-staging.firebaseapp.com https://kkb-production.firebaseapp.com https://kaggle-metastore-test.firebaseapp.com https://kaggle-metastore.firebaseapp.com https://apis.google.com https://content-sheets.googleapis.com/ https://accounts.google.com/ https://storage.googleapis.com https://docs.google.com https://drive.google.com; base-uri 'none'; report-uri https://csp.withgoogle.com/csp/kaggle/20201130;", 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
